@startuml
title Layer Activity Diagramm

|Nutzer|
start
:Startet die Anwendung;
:Importiert ein Bild;

|System|
:Skaliert Originalbild auf Default Größe;
:Nimmt Durchschnitt der Farben für Downscale;
:Erstellt Layer nach Default-Einstellungen;
:Zeigt erste Vorschau der Vorlage;

|Nutzer|
:Passt Layeranzahl an;
:Drückt "Vorschau erstellen";

|System|
:Stetzt die Variablen der Layeranzahl auf die neue Anzahl;
:Zeigt aktualisierte Vorschau;

|Nutzer|
:Wählt Grenzen & Dimensionen der Layer;
:Drückt "Vorschau erstellen";

|System|
:Setzt die Variablen der Layer Grenzen auf die neue Position;
:Zeigt aktualisierte Vorschau;

|Nutzer|
:Speichert Projekt ab;
stop
@enduml 

