@startuml
title Layer Activity Diagramm

|Nutzer|
start
:Startet die Anwendung;
:Importiert ein Bild;

|System|
:Skaliert Originalbild auf neue Größe;
:Nimmt Average der Farben für Downscale;
:Erstellt Layer nach Default-Einstellungen;
:Zeigt erste Vorschau der Vorlage;

|Nutzer|
:Passt Layeranzahl an;
:Drückt "Vorschau erstellen";

|System|
:Passt die Layeranzahl an;
:Zeigt aktualisierte Vorschau;

|Nutzer|
:Wählt Grenzen & Dimensionen der Layer;
:Drückt "Vorschau erstellen";

|System|
:Passt Grenzen & Dimensionen der Layer;
:Zeigt aktualisierte Vorschau;

|Nutzer|
:Speichert Projekt ab;
stop
@enduml 

