@startuml
title Preview Activity Diagramm

|Nutzer|
start
:Startet die Anwendung;
:Importiert ein Bild;

|System|
:Skaliert Originalbild auf Default Größe;
:Nimmt Durchschnitt der Farben für Downscale;
:Erstellt Layer nach Default-Einstellungen;
:Zeigt erste Vorschau der Vorlage;

|Nutzer|
:Sieht Vorschau und beschließt, eine Änderung vorzunehmen;
:Drückt "Vorschau erstellen";

|System|
:Skaliert das Bild auf die neuen Dimensionen;
:Wendet die Farbreduktion auf die neuen Dimensionen an;
:Passt die Layerdimensionen auf die neuen Dimensionen an;
:Erstellt neue Vorschau;
:Zeigt aktualisierte Vorschau;

|Nutzer|
:Sieht aktualisierte Vorschau;
stop

@enduml
