@startuml
title Preview Activity Diagramm

|Nutzer|
start
:Startet die Anwendung;
:Importiert ein Bild;

|System|
:Zeigt Vorschau der Vorlage;

|Nutzer|
:Sieht Vorschau und beschließt, eine Änderung vorzunehmen;
:Drückt "Vorschau erstellen";

|System|
:Nimmt Änderung vor;
:Erstellt neue Vorschau;
:Zeigt aktualisierte Vorschau;

|Nutzer|
:Sieht aktualisierte Vorschau;
stop

@enduml
