@startuml
title Layer Activity Diagramm

|Nutzer|
start
:Startet die Anwendung;

|System|
:Initialisiert Anwendung;
if (Gespeichertes Projekt vorhanden?) then (Ja)
  :Lädt letztes Projekt;
else (Nein)
  :Erstellt neues Default-Projekt;
endif
:Zeigt Defaultscreen;

|Nutzer|
:Importiert ein Bild;

|System|
:Skaliert Originalbild auf neue Größe;
:Nimmt Average der Farben für Downscale;
:Erstellt Layer nach Default-Einstellungen;
:Zeigt erste Vorschau der Vorlage;

|Nutzer|
:Passt Layeranzahl an;
:Wählt Grenzen & Dimensionen der Layer;
:Drückt "Vorschau erstellen";

|System|
:Passt die Layeranzahl an;
:Setzt die Grenzen und Dimensionen neu;
:Zeigt aktualisierte Vorschau;

|Nutzer|
:Speichert Projekt ab;
stop
@enduml 

